# -*- coding: utf-8 -*-
"""러교론 사이트

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bw4WZCs7g8WDXOD8KKVoeMEGw9Qnkxh4
"""

import re
import streamlit as st
from pymystem3 import Mystem
from googletrans import Translator

st.set_page_config(page_title="러시아어 텍스트 분석기", layout="wide")
st.title("러시아어 텍스트 분석기")

# 초기화
if "clicked_word" not in st.session_state:
    st.session_state.clicked_word = None

# 도구
mystem = Mystem()
translator = Translator()

@st.cache_data(show_spinner=False)
def lemmatize_ru(word: str) -> str:
    lemmas = mystem.lemmatize(word)
    return (lemmas[0] if lemmas else word).strip()

@st.cache_data(show_spinner=False)
def translate_ru_ko(word: str) -> str:
    try:
        return translator.translate(word, src="ru", dest="ko").text
    except Exception:
        return "(번역 실패)"

# 입력
text = st.text_area("텍스트를 입력하세요", "Человек идёт по улице. Это тестовая строка.")

# 토큰화 (단어/문장부호 분리, 공백은 출력 시 처리)
tokens = re.findall(r"\w+|[^\w\s]", text, flags=re.UNICODE)

left, right = st.columns([2, 1], gap="large")

with left:
    st.subheader("텍스트 분석 결과")
    st.caption("단어 버튼을 클릭하면 오른쪽에 기본형(lemma)과 한국어 뜻이 표시됩니다.")
    # 단어는 버튼(세로 배열), 부호는 그대로 표시
    for i, tok in enumerate(tokens):
        if re.match(r"\w+", tok, flags=re.UNICODE):
            if st.button(tok, key=f"tok_{i}"):
                st.session_state.clicked_word = tok
        else:
            st.markdown(tok)

    # 유틸: 상태 초기화
    with st.expander("초기화"):
        if st.button("🔄 선택 초기화"):
            st.session_state.clicked_word = None
            st.rerun()

with right:
    st.subheader("📚 단어 정보")
    cw = st.session_state.clicked_word
    if cw:
        lemma = lemmatize_ru(cw)
        meaning = translate_ru_ko(cw)
        st.markdown(f"**선택된 단어:** {cw}")
        st.markdown(f"**기본형(lemma):** *{lemma}*")
        st.markdown(f"**한국어 뜻:** {meaning}")
    else:
        st.info("왼쪽에서 단어를 클릭하면 여기 표시됩니다.")

# 보조: 직접 검색
st.divider()
st.subheader("🔍 직접 검색")
q = st.text_input("단어를 직접 입력해 검색할 수도 있어요.", "")
if q:
    lemma = lemmatize_ru(q)
    meaning = translate_ru_ko(q)
    st.markdown(f"**입력 단어:** {q}")
    st.markdown(f"**기본형(lemma):** *{lemma}*")
    st.markdown(f"**한국어 뜻:** {meaning}")
